add_newline = false

[line_break]
disabled = true

[character]                  
success_symbol = "[λ](bold green)"
error_symbol =   "[λ](bold red)"
#λ


# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
