#!/usr/bin/env bash
#

# Defining our web browser.
DMBROWSER="brave"

# An array of search engines.  You can edit this list to add/remove
# search engines. The format must be: "engine_name - url".
# The url format must allow for the search keywords at the end of the url.
# For example: https://www.amazon.com/s?k=XXXX searches Amazon for 'XXXX'.
declare -a options=(
"amazon - https://www.amazon.co.uk/s?k="
"archaur - https://aur.archlinux.org/packages/?O=0&K="
"archpkg - https://archlinux.org/packages/?sort=&q="
"archwiki - https://wiki.archlinux.org/index.php?search="
"arxiv - https://arxiv.org/search/?searchtype=all&source=header&query="
"bbcnews - https://www.bbc.co.uk/search?q="
"bing - https://www.bing.com/search?q="
"cliki - https://www.cliki.net/site/search?query="
"debianpkg - https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords="
"discogs - https://www.discogs.com/search/?&type=all&q="
"duckduckgo - https://duckduckgo.com/?q="
"ebay - https://www.ebay.co.uk/sch/i.html?&_nkw="
"github - https://github.com/search?q="
"gitlab - https://gitlab.com/search?search="
"google - https://www.google.co.uk/search?q="
"googleimages - https://www.google.co.uk/search?hl=en&tbm=isch&q="
"googlenews - https://news.google.com/search?q="
"imdb - https://www.imdb.com/find?q="
"reddit - https://www.reddit.com/search/?q="
"thesaurus - https://www.thesaurus.com/misspelling?term="
"translate - https://translate.google.com/?sl=auto&tl=en&text="
"urban - https://www.urbandictionary.com/define.php?term="
"webster - https://www.merriam-webster.com/dictionary/"
"wikipedia - https://en.wikipedia.org/wiki/"
"wiktionary - https://en.wiktionary.org/wiki/"
"wolfram - https://www.wolframalpha.com/input/?i="
"youtube - https://www.youtube.com/results?search_query="
"quit"
)

# Picking a search engine.
while [ -z "$engine" ]; do
enginelist=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Choose search engine:') || exit
engineurl=$(echo "$enginelist" | awk '{print $NF}')
engine=$(echo "$enginelist" | awk '{print $1}')
done

# Searching the chosen engine.
while [ -z "$query" ]; do
    if [[ "$engine" == "quit" ]]; then
        echo "Program terminated." && exit 0
    else
        query=$(echo "$engine" | dmenu -p 'Enter search query:') || exit
    fi
done

# Display search results in web browser
$DMBROWSER "$engineurl""$query"
