#! /bin/sh

### autostart ###
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
#xset r rate 360 60 -b -dpms &
xset r rate 360 60 &
#feh --bg-max --randomize ~/Wallpapers/* &
xwallpaper --center /home/jay/Pictures/wallpapers/2.png
lxsession &
$HOME/.config/polybar/launch.sh
picom -b &
#nm-applet &
dunst &
unclutter -idle 2 &
#redshift -O3500
xset s off &
#pgrep bspswallow || bspswallow &


bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           20

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config borderless_monocle      true
bspc config focus_follows_pointer   true
bspc config top_padding             30

### colors border ###
bspc config normal_border_color     "#928374"
bspc config active_border_color     "#d79921"
bspc config focused_border_color    "#ebdbb2"
bspc config presel_feedback_color   "#4c566a"
bspc config urgent_border_color     "#b16286"

### ALWAYS FLOATING ###
bspc rule -a feh            state=floating center=on
bspc rule -a Sxiv           state=floating center=on
bspc rule -a mpv            state=floating center=on sticky=on
bspc rule -a Lxappearance   state=floating center=on


bspc rule -a Emacs   state=tiled

# 1
bspc rule -a kitty              desktop='^1' focus=on follow=on
bspc rule -a Alacritty          desktop='^1' focus=on follow=on
bspc rule -a Xterm              desktop='^1' focus=on follow=on
bspc rule -a xfce4-terminal     desktop='^1' focus=on follow=on
bspc rule -a urxvt              desktop='^1' focus=on follow=on
# 2
bspc rule -a Chromium       desktop='^2' focus=on follow=on border=off
bspc rule -a Brave-browser  desktop='^2' focus=on follow=on border=off
bspc rule -a firefox        desktop='^2' focus=on follow=on border=off
# 3
bspc rule -a Thunar         desktop='^3' focus=on follow=on
bspc rule -a Pcmanfm        desktop='^3' focus=on follow=on
bspc rule -a qBittorrent    desktop='^3' focus=on follow=on
# 4
bspc rule -a TelegramDesktop desktop='^4' focus=on follow=on
# 5
bspc rule -a Virt-manager desktop='^5' state=floating focus=on follow=on
