#! /bin/bash

auto-reload yes
reload-time 1
reload-threads 100

bind-key j down
bind-key k up

browser "firefox %u"
#macro t set browser "mpv %u" ; open-in-browser ; set browser "brave %u"
#macro v set browser "setsid -f mpv" ; open-in-browser ; set browser linkhandler
macro v set browser "setsid -f mpv --really-quiet --no-terminal" ; open-in-browser ; set browser firefox

highlight feedlist "---.*---" red default bold
highlight feedlist ".*0/0.." default default invis

color background default default
color listnormal default default
color listnormal_unread blue black
color listfocus color16 cyan
color listfocus_unread color16 cyan
color info default black
color article default default

highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default

highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default
